# Generated by Django 4.2.5 on 2023-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='name')),
                ('language', models.CharField(blank=True, max_length=25, null=True, verbose_name='language')),
            ],
            options={
                'verbose_name': 'Фремворк',
                'verbose_name_plural': 'Фремворки',
            },
        ),
    ]
